### ISSUE TITLE
how to test projection via slots

### ISSUE THREAD

**Issue by Hotell** [treshugart/bore#17]
we are dealing with question how to test projected content via slots 
https://github.com/wc-catalogue/blaze-elements/issues/238

Just wanted to ask how do you do it within atlassian. Any suggestions are more than welcome!

**Comment by Hotell** [comment]
on thing that comes to mind is `assignedSlot` or `assignedNodes()` but that dosn't work in browsers which are using polyfill for shadow dom https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#workwithslots

**Comment by treshugart** [comment]
As discussed IRL, the best thing to do here is probably to only go as far as to test to ensure the slots you expect to exist, are there. If you test slotting, then you're testing things that should already be tested by the polyfills and browsers.

Will close this, but if there's anything else to action here, let's address it!
