### ISSUE TITLE
readme inconsistencies

### ISSUE THREAD

**Issue by moebiusmania** [treshugart/bore#21]
hi!
I just discovered this awesome project and wanted to got started in testing Web Components with Bore on Node.js, but unfortunately there are a couple of small gotchas on the readme file of this repo:

- https://github.com/skatejs/ssr#testing-in-node the hash on the link doesn't seem to exist, and the first sentence on that readme says that the code has moved to the monorepo
- https://gist.github.com/treshugart/719dad9c3be6e048b9563309cf37d3c1 its 404

tomorrow I will slowly check out the docs to better understand, but if you could fix this I think it would be great for newcomers 😃 

thanks for the great work man!

**Comment by treshugart** [comment]
Hey @moebiusmania, thanks for reporting. I've updated the README to suit. I linked to the monorepo and removed the gist link because the docs should be good enough. Cheers!
